### ISSUE TITLE
Add option to delete categories

### ISSUE THREAD

**Issue by vyankatesh24** [vyankatesh24/ExpenseTracker#1]
### Expected Behaviour
* There should be an option to delete categories.

### What to do?
* Open dialog when clicked on `Category Name`.
* Add options `Edit` and `Delete` . 
* Implement Logic for `Delete` Option.

**Comment by codersanjeev** [comment]
I want to work on this issue @vyankatesh24

**Comment by vyankatesh24** [comment]
Sure @thedevelopersanjeev 
Go Ahead :+1:
