### ISSUE TITLE
Add option to Edit Categories

### ISSUE THREAD

**Issue by vyankatesh24** [vyankatesh24/ExpenseTracker#2]
### Expected Behaviour
* There should be an option to Edit categories.

### What to do?
* Open dialog when clicked on `Category Name`.
* Add options `Edit` and `Delete` . 
* Implement Logic for `Edit` Option.

**Comment by codersanjeev** [comment]
I am working on this issue

**Comment by vyankatesh24** [comment]
Fixed by #8
