### ISSUE TITLE
Implement Add Transaction Feature

### ISSUE THREAD

**Issue by vyankatesh24** [vyankatesh24/ExpenseTracker#4]
### Expected Behaviour
* There should be an option to Add Transaction.

### What to do?
* Open dialog when clicked on `FAB` to input transaction information.
* Create a database table for transactions. 
* Implement Logic for same.

**Comment by codersanjeev** [comment]
I am working on this issue @vyankatesh24

**Comment by vyankatesh24** [comment]
Ok

**Comment by codersanjeev** [comment]
what should be the schema of the transactions table? @vyankatesh24

**Comment by vyankatesh24** [comment]
Columns will be Date, Category, Amount and note for transaction 
You may add some to this list  if necessary.
